# Version for the build. We make it clear that it's
# Appveyor as this isn't a version we expect to make
# it elsewhere...
version: 1.0.{build}-appveyor

image: Visual Studio 2017

branches:
  only:
    - master

environment:
  COVERALLS_REPO_TOKEN:
    secure: 0MrjEwujECMnIaBkI76fNmCpKy5jr9rZx0rAFOM+41frhVfy2r0ldzzoFC4bvGig
  SONARCLOUD_LOGIN:
    secure: TLTw/fHFIX1A7sfXh/trJpXiv5pBiB4GzhlRKIVTsodKA9hl1fsstXsIHyb/M/ZH

install:
- ps: |
    Write-Host "Installing .NET Core SDK..." -ForegroundColor Cyan
    Write-Host "Downloading..."
    $exePath = "$env:TEMP\dotnet-sdk.exe"
    (New-Object Net.WebClient).DownloadFile('https://download.visualstudio.microsoft.com/download/pr/31b5b67f-b787-4f73-a728-5ec61f10a4de/be6430bcd9a62f610cd9f12f8cc2c736/dotnet-sdk-3.0.100-preview3-010431-win-x64.exe', $exePath)
    Write-Host "Installing..."
    cmd /c start /wait "$exePath" /quiet /norestart
    del $exePath
    Write-Host "Installed" -ForegroundColor Green
    Write-Host "Installing SonarScanner..." -ForegroundColor Cyan
    dotnet tool install --global dotnet-sonarscanner
    Write-Host "Installed" -ForegroundColor Green

# Perform the build.
build_script:
  - ps: |
      dotnet sonarscanner begin `
        /k:"nodatime" `
        /n:"Noda Time" `
        /v:"$env:APPVEYOR_BUILD_VERSION" `
        /o:"codeconditioner" `
        /d:"sonar.host.url=https://sonarqube.com" `
        /d:"sonar.login=$env:SONARCLOUD_LOGIN" `
        /d:"sonar.c.file.suffixes=-" `
        /d:"sonar.cpp.file.suffixes=-" `
        /d:"sonar.objc.file.suffixes=-" `
        /d:"sonar.cs.dotcover.reportsPaths=coverage/coverage.html"
  - bash build/appveyor.sh
  - ps: dotnet sonarscanner end /d:"sonar.login=$env:SONARCLOUD_LOGIN"
  - choco install codecov
  - codecov -f coverage/coverage.html

# The tests are run as part of the build.
test: off

artifacts:
  - path: coverage/coverage.html
    name: Coverage
